name: Release move-tool

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for this release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
        
jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version: '1.22'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -v -o move-tool-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.inputs.version || github.ref }}
        if [ "${{ matrix.goos }}" = "windows" ]; then
          mv move-tool-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.inputs.version || github.ref }} move-tool-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.inputs.version || github.ref }}.exe
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: move-tool-${{ matrix.goos }}-${{ matrix.goarch }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.event.inputs.version || github.ref }}
        files: |
          move-tool-*
        tag_name: ${{ github.event.inputs.version || github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
